"""All user-facing text. en is the source of truth. hi/kn were drafted with AI assistance and reviewed by the developers; an independent native-speaker review has not been done.
Anything missing in hi/kn falls back to English (t() below) so a missing string can never crash a live demo."""
S = {
"consent": {"en": "Namaste, I am Hamsa. I check whether a medicine batch has any warning in official records.\n\nTo do this I use the batch number or photo you send, and your phone number (saved only as a code that cannot be traced back). Photos are deleted after 30 days. Send DELETE at any time to erase your data.\n\nDo you agree?", "hi": "नमस्ते! मैं *हंसा* हूँ — मैं जाँचता हूँ कि किसी दवा के बैच पर सरकारी रिकॉर्ड में कोई चेतावनी है या नहीं।\n\nइसके लिए मैं आपका भेजा बैच नंबर/फ़ोटो और आपका फ़ोन नंबर (केवल एक अपरिवर्तनीय कोड के रूप में) उपयोग करूँगा। फ़ोटो 30 दिन बाद मिटा दी जाती हैं। अपना डेटा मिटाने के लिए कभी भी *DELETE* लिखें।\n\nक्या आप सहमत हैं?", "kn": "ನಮಸ್ಕಾರ! ನಾನು *ಹಂಸ* — ಔಷಧದ ಬ್ಯಾಚ್‌ಗೆ ಸರ್ಕಾರಿ ದಾಖಲೆಗಳಲ್ಲಿ ಎಚ್ಚರಿಕೆ ಇದೆಯೇ ಎಂದು ಪರಿಶೀಲಿಸುತ್ತೇನೆ.\n\nಇದಕ್ಕಾಗಿ ನೀವು ಕಳುಹಿಸುವ ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ/ಫೋಟೋ ಮತ್ತು ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ (ಬದಲಾಯಿಸಲಾಗದ ಕೋಡ್ ರೂಪದಲ್ಲಿ ಮಾತ್ರ) ಬಳಸುತ್ತೇನೆ. ಫೋಟೋಗಳನ್ನು 30 ದಿನಗಳ ನಂತರ ಅಳಿಸಲಾಗುತ್ತದೆ. ಡೇಟಾ ಅಳಿಸಲು ಯಾವಾಗ ಬೇಕಾದರೂ *DELETE* ಎಂದು ಬರೆಯಿರಿ.\n\nನೀವು ಒಪ್ಪುತ್ತೀರಾ?"},
"btn_agree": {"en": "I agree", "hi": "मैं सहमत हूँ", "kn": "ಒಪ್ಪುತ್ತೇನೆ"},
"btn_decline":{"en": "No thanks", "hi": "नहीं", "kn": "ಬೇಡ"},
"declined": {"en": "That is fine. Nothing was saved. Message me whenever you want to check a medicine.", "hi": "कोई बात नहीं — कुछ भी सहेजा नहीं गया। मन बदले तो कभी भी संदेश भेजें।", "kn": "ಚಿಂತೆಯಿಲ್ಲ — ಏನನ್ನೂ ಉಳಿಸಿಕೊಂಡಿಲ್ಲ. ಮನಸ್ಸು ಬದಲಾದರೆ ಯಾವಾಗ ಬೇಕಾದರೂ ಸಂದೇಶ ಕಳುಹಿಸಿ."},
"lang_prompt":{"en": "Choose your language / भाषा चुनें / ಭಾಷೆ ಆರಿಸಿ", "hi": "भाषा चुनें / Choose your language / ಭಾಷೆ ಆರಿಸಿ",
               "kn": "ಭಾಷೆ ಆರಿಸಿ / Choose your language / भाषा चुनें"},
"menu": {"en": "Send the batch number printed on the pack (for example AX2291), or a clear photo of the pack showing the QR code and the label.", "hi": "पैक पर छपा *बैच नंबर* भेजें (जैसे AX2291), या पैक की *साफ़ फ़ोटो* भेजें जिसमें QR / DataMatrix कोड और लेबल दिखे।", "kn": "ಪ್ಯಾಕ್ ಮೇಲೆ ಮುದ್ರಿತ *ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ* ಕಳುಹಿಸಿ (ಉದಾ. AX2291), ಅಥವಾ QR / DataMatrix ಕೋಡ್ ಮತ್ತು ಲೇಬಲ್ ಕಾಣುವ *ಸ್ಪಷ್ಟ ಫೋಟೋ* ಕಳುಹಿಸಿ."},
"ask_expiry": {"en": "I do not have batch {b} in my records. What expiry date is printed on the pack? Reply like 03/2028, or send SKIP.", "hi": "बैच *{b}* मेरे रजिस्टर में नहीं है। पैक पर एक्सपायरी तारीख क्या छपी है? जैसे *03/2028* लिखें, या *SKIP* लिखें।", "kn": "ಬ್ಯಾಚ್ *{b}* ನನ್ನ ದಾಖಲೆಯಲ್ಲಿ ಇಲ್ಲ. ಪ್ಯಾಕ್ ಮೇಲೆ ಮುದ್ರಿತ ಅವಧಿ ಮುಕ್ತಾಯ ದಿನಾಂಕ ಯಾವುದು? *03/2028* ಎಂದು ಬರೆಯಿರಿ, ಅಥವಾ *SKIP* ಎಂದು ಬರೆಯಿರಿ."},
"wait": {"en": "Please wait a few seconds before the next check.", "hi": "कृपया कुछ सेकंड रुकें — फिर दूसरा बैच जाँच सकते हैं।", "kn": "ದಯವಿಟ್ಟು ಕೆಲವು ಸೆಕೆಂಡ್ ಕಾಯಿರಿ."},
"qr_fail": {"en": "I could not read the code in that photo. Please type the batch number printed on the pack.", "hi": "उस फ़ोटो में मैं वैध कोड नहीं पढ़ सका। कोई बात नहीं — पैक पर छपा *बैच नंबर* टाइप करें।", "kn": "ಆ ಫೋಟೋದಲ್ಲಿ ಮಾನ್ಯ ಕೋಡ್ ಓದಲಾಗಲಿಲ್ಲ. ಚಿಂತೆಯಿಲ್ಲ — ಪ್ಯಾಕ್ ಮೇಲಿನ *ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ* ಟೈಪ್ ಮಾಡಿ."},
"read_text": {"en": "Details read from your photo\n\n{rows}\n\nAutomatic reading can make mistakes. Please check against the pack.", "hi": "आपकी फ़ोटो से पढ़ी गई जानकारी\n\n{rows}\n\nस्वचालित पढ़ाई में गलती हो सकती है। कृपया पैक से मिलान करें।", "kn": "ನಿಮ್ಮ ಫೋಟೋದಿಂದ ಓದಿದ ವಿವರಗಳು\n\n{rows}\n\nಸ್ವಯಂಚಾಲಿತ ಓದಿನಲ್ಲಿ ತಪ್ಪುಗಳಿರಬಹುದು. ದಯವಿಟ್ಟು ಪ್ಯಾಕ್‌ನೊಂದಿಗೆ ಹೋಲಿಸಿ ನೋಡಿ."},
"f_manufacturer": {"en": "Manufacturer", "hi": "निर्माता", "kn": "ತಯಾರಕ"},
"f_batch":    {"en": "Batch", "hi": "बैच", "kn": "ಬ್ಯಾಚ್"},
"f_expiry":   {"en": "Expiry", "hi": "समाप्ति", "kn": "ಅವಧಿ ಮುಕ್ತಾಯ"},
"f_licence":  {"en": "Mfg. licence", "hi": "विनिर्माण लाइसेंस", "kn": "ತಯಾರಿಕಾ ಪರವಾನಗಿ"},
"f_register": {"en": "In our records", "hi": "हमारे रिकॉर्ड में", "kn": "ನಮ್ಮ ದಾಖಲೆಯಲ್ಲಿ"},
"f_missing":  {"en": "Not found: {names}", "hi": "नहीं मिला: {names}", "kn": "ಸಿಗಲಿಲ್ಲ: {names}"},
"r_nsq": {"en": "CDSCO, the government drug regulator, has marked this batch as failing quality tests{detail}.", "hi": "CDSCO (सरकारी दवा नियामक) ने इस बैच को गुणवत्ता जाँच में फ़ेल बताया है{detail}।", "kn": "CDSCO (ಸರ್ಕಾರಿ ಔಷಧ ನಿಯಂತ್ರಕ) ಈ ಬ್ಯಾಚ್ ಗುಣಮಟ್ಟ ಪರೀಕ್ಷೆಯಲ್ಲಿ ವಿಫಲವಾಗಿದೆ ಎಂದು ತಿಳಿಸಿದೆ{detail}."},
"r_nsq_unavail": {"en": "I could not check the official warning list just now. Please confirm with a pharmacist.", "hi": "अभी मैं सरकारी चेतावनी सूची नहीं देख सका। कृपया फ़ार्मासिस्ट से पुष्टि करें।", "kn": "ಈಗ ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆ ಪಟ್ಟಿಯನ್ನು ಪರಿಶೀಲಿಸಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಔಷಧಿಕಾರರೊಂದಿಗೆ ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ."},
"r_nsq_fixed": {"en": "An earlier warning for this batch was corrected. It has no current listing.", "hi": "इस बैच की पहले की चेतावनी सुधार दी गई है — अभी कोई सूचीबद्ध चेतावनी नहीं है।", "kn": "ಈ ಬ್ಯಾಚ್‌ಗೆ ಮೊದಲಿನ ಎಚ್ಚರಿಕೆಯನ್ನು ಸರಿಪಡಿಸಲಾಗಿದೆ — ಈಗ ಯಾವುದೇ ಪಟ್ಟಿ ಇಲ್ಲ."},
"r_label": {"en": "The label printed on the pack does not match the code.", "hi": "पैक पर छपा लेबल कोड से मेल नहीं खाता।", "kn": "ಪ್ಯಾಕ್ ಮೇಲಿನ ಲೇಬಲ್ ಕೋಡ್‌ಗೆ ಹೊಂದುತ್ತಿಲ್ಲ."},
"r_label_unsure": {"en": "I could not read the printed label clearly. Please retake the photo or type the manufacturer's name.", "hi": "छपा लेबल साफ़ नहीं पढ़ सका। फ़ोटो दोबारा लें या निर्माता का नाम लिखें।", "kn": "ಮುದ್ರಿತ ಲೇಬಲ್ ಸ್ಪಷ್ಟವಾಗಿ ಓದಲಾಗಲಿಲ್ಲ. ಫೋಟೋ ಮತ್ತೆ ತೆಗೆಯಿರಿ ಅಥವಾ ತಯಾರಕರ ಹೆಸರು ಟೈಪ್ ಮಾಡಿ."},
"r_visual": {"en": "The photo is blurry or cut off, so this check is less reliable. Please retake it in good light with the whole pack in view.", "hi": "फ़ोटो धुंधली या कटी हुई है, इसलिए यह जाँच कम भरोसेमंद है। अच्छी रोशनी में पूरा पैक दिखाकर दोबारा लें।", "kn": "ಫೋಟೋ ಮಸುಕಾಗಿದೆ ಅಥವಾ ಕತ್ತರಿಸಿದೆ, ಆದ್ದರಿಂದ ಈ ಪರಿಶೀಲನೆ ಕಡಿಮೆ ನಂಬಲರ್ಹ. ಒಳ್ಳೆಯ ಬೆಳಕಿನಲ್ಲಿ ಪೂರ್ಣ ಪ್ಯಾಕ್ ಕಾಣುವಂತೆ ಮತ್ತೆ ತೆಗೆಯಿರಿ."},
"r_code": {"en": "I could not read the code on the pack properly.", "hi": "पैक का कोड ठीक से नहीं पढ़ा जा सका।", "kn": "ಪ್ಯಾಕ್‌ನ ಕೋಡ್ ಸರಿಯಾಗಿ ಓದಲಾಗಲಿಲ್ಲ."},
"r_replay": {"en": "This code was scanned in two faraway places within one day. The pack may be a copy.", "hi": "इस पैक का कोड एक दिन में दो दूर-दूर की जगहों पर स्कैन हुआ — यह नकल हो सकती है।", "kn": "ಈ ಪ್ಯಾಕ್‌ನ ಕೋಡ್ ಒಂದು ದಿನದಲ್ಲಿ ಬಹಳ ದೂರದ ಎರಡು ಸ್ಥಳಗಳಲ್ಲಿ ಸ್ಕ್ಯಾನ್ ಆಗಿದೆ — ಇದು ನಕಲಾಗಿರಬಹುದು."},
"r_esc": {"en": "Two separate warnings were found on this pack. This is not an official CDSCO listing.", "hi": "दो अलग चेतावनियाँ मिलीं। यह CDSCO की आधिकारिक सूची नहीं है।", "kn": "ಎರಡು ಪ್ರತ್ಯೇಕ ಎಚ್ಚರಿಕೆಗಳು ಸಿಕ್ಕಿವೆ. ಇದು CDSCO ಅಧಿಕೃತ ಪಟ್ಟಿ ಅಲ್ಲ."},
"r_expired": {"en": "Also expired: this medicine is past its expiry date.", "hi": "यह दवा एक्सपायर भी हो चुकी है।", "kn": "ಈ ಔಷಧದ ಅವಧಿಯೂ ಮುಗಿದಿದೆ."},
"r_asof": {"en": "Data as of {date}. Live records are not available right now.", "hi": "डेटा {date} तक का है। लाइव रिकॉर्ड अभी उपलब्ध नहीं हैं।", "kn": "{date} ವರೆಗಿನ ಡೇಟಾ. ಲೈವ್ ದಾಖಲೆಗಳು ಈಗ ಲಭ್ಯವಿಲ್ಲ."},
"r_src": {"en": "Source: {ref}", "hi": "स्रोत: {ref}", "kn": "ಮೂಲ: {ref}"},
"r_clear": {"en": "No problem found with: {names}.", "hi": "इनमें कोई समस्या नहीं मिली: {names}।", "kn": "ಇವುಗಳಲ್ಲಿ ಸಮಸ್ಯೆ ಕಂಡುಬಂದಿಲ್ಲ: {names}."},
"r_unchecked": {"en": "Not checked: pack code and label. Send a photo of the pack to check them.", "hi": "जाँचा नहीं गया: पैक का कोड और लेबल। इन्हें जाँचने के लिए पैक की फ़ोटो भेजें।", "kn": "ಪರಿಶೀಲಿಸಿಲ್ಲ: ಪ್ಯಾಕ್‌ನ ಕೋಡ್ ಮತ್ತು ಲೇಬಲ್. ಪರಿಶೀಲಿಸಲು ಪ್ಯಾಕ್‌ನ ಫೋಟೋ ಕಳುಹಿಸಿ."},
"c_nsq_status": {"en": "official warning list", "hi": "सरकारी चेतावनी सूची", "kn": "ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆ ಪಟ್ಟಿ"},
"c_expiry_status": {"en": "expiry date", "hi": "एक्सपायरी तारीख", "kn": "ಅವಧಿ ಮುಕ್ತಾಯ ದಿನಾಂಕ"},
"c_label_consistency": {"en": "label matches code", "hi": "लेबल कोड से मेल खाता है", "kn": "ಲೇಬಲ್ ಕೋಡ್‌ಗೆ ಹೊಂದುತ್ತದೆ"},
"c_code_validity": {"en": "code readable", "hi": "कोड पढ़ा जा सका", "kn": "ಕೋಡ್ ಓದಲಾಯಿತು"},
"footer": {"en": "Reply WHY for details, or DELETE to erase your data.", "hi": "विवरण के लिए WHY, डेटा मिटाने के लिए DELETE लिखें।", "kn": "ವಿವರಗಳಿಗೆ WHY, ಡೇಟಾ ಅಳಿಸಲು DELETE ಎಂದು ಬರೆಯಿರಿ."},
"disclaimer": {"en": "Not medical advice. Please ask your pharmacist or doctor.", "hi": "यह चिकित्सा सलाह नहीं है — अपने फ़ार्मासिस्ट या डॉक्टर से पूछें।", "kn": "ಇದು ವೈದ್ಯಕೀಯ ಸಲಹೆ ಅಲ್ಲ — ನಿಮ್ಮ ಔಷಧಿಕಾರ ಅಥವಾ ವೈದ್ಯರನ್ನು ಕೇಳಿ."},
"btn_report": {"en": "Report this batch", "hi": "रिपोर्ट करें", "kn": "ವರದಿ ಮಾಡಿ"},
"btn_again":  {"en": "Check another", "hi": "दूसरा जाँचें", "kn": "ಇನ್ನೊಂದು ಪರಿಶೀಲಿಸಿ"},
"btn_dispute":{"en": "Dispute (makers)", "hi": "आपत्ति (निर्माता)", "kn": "ಆಕ್ಷೇಪ (ತಯಾರಕ)"},
"next": {"en": "What would you like to do next?", "hi": "आगे क्या?", "kn": "ಮುಂದೇನು?"},
"report_type": {"en": "What is wrong with this pack?", "hi": "समस्या क्या है?", "kn": "ಸಮಸ್ಯೆ ಏನು?"},
"btn_rt1":    {"en": "Looks fake", "hi": "नकली लगता है", "kn": "ನಕಲಿ ಎನಿಸುತ್ತದೆ"},
"btn_rt2":    {"en": "Seal tampered", "hi": "सील खुली है", "kn": "ಸೀಲ್ ತೆರೆದಿದೆ"},
"btn_rt3":    {"en": "Other", "hi": "अन्य", "kn": "ಇತರೆ"},
"report_desc": {"en": "Tell me what you noticed in one message, or send SKIP.", "hi": "जो आपने देखा एक संदेश में लिखें (या *SKIP*)।", "kn": "ನೀವು ಗಮನಿಸಿದ್ದನ್ನು ಒಂದು ಸಂದೇಶದಲ್ಲಿ ಬರೆಯಿರಿ (ಅಥವಾ *SKIP*)."},
"report_ok": {"en": "Thank you. Your report has been sent to the regulator for review. It is never made public.", "hi": "धन्यवाद। आपकी रिपोर्ट नियामक की समीक्षा के लिए दर्ज हुई (स्थिति: *open*)। यह सार्वजनिक नहीं की जाती।", "kn": "ಧನ್ಯವಾದ. ನಿಮ್ಮ ವರದಿಯನ್ನು ನಿಯಂತ್ರಕರ ಪರಿಶೀಲನೆಗೆ ದಾಖಲಿಸಲಾಗಿದೆ (ಸ್ಥಿತಿ: *open*). ಇದನ್ನು ಸಾರ್ವಜನಿಕವಾಗಿ ತೋರಿಸುವುದಿಲ್ಲ."},
"report_cap": {"en": "You've reached today's limit of 5 reports. Please try again tomorrow.",
               "hi": "आज की 5 रिपोर्ट की सीमा पूरी हो गई। कृपया कल फिर कोशिश करें।",
               "kn": "ಇಂದಿನ 5 ವರದಿಗಳ ಮಿತಿ ತಲುಪಿದೆ. ದಯವಿಟ್ಟು ನಾಳೆ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ."},
"dispute_email": {"en": "Dispute for batch {b} (manufacturers only).\nPlease type your official company email address. I will check its domain against registered manufacturers.", "hi": "बैच *{b}* पर निर्माता / फ़ार्मेसी की आपत्ति।\nकृपया अपना *आधिकारिक कंपनी ईमेल पता* लिखें (प्रोटोटाइप जाँच: हम ईमेल डोमेन को पंजीकृत निर्माताओं से मिलाते हैं)।", "kn": "ಬ್ಯಾಚ್ *{b}* ಗೆ ತಯಾರಕ / ಔಷಧಾಲಯದ ಆಕ್ಷೇಪ.\nದಯವಿಟ್ಟು ನಿಮ್ಮ *ಅಧಿಕೃತ ಕಂಪನಿ ಇಮೇಲ್ ವಿಳಾಸ* ಟೈಪ್ ಮಾಡಿ (ಪ್ರೋಟೋಟೈಪ್ ಪರಿಶೀಲನೆ: ನೋಂದಾಯಿತ ತಯಾರಕರೊಂದಿಗೆ ಇಮೇಲ್ ಡೊಮೇನ್ ಹೋಲಿಸುತ್ತೇವೆ)."},
"dispute_bad": {"en": "That email domain isn't a registered manufacturer domain, so I can't file the dispute.", "hi": "यह ईमेल डोमेन किसी पंजीकृत निर्माता का नहीं है, इसलिए मैं विवाद दर्ज नहीं कर सकता।", "kn": "ಈ ಇಮೇಲ್ ಡೊಮೇನ್ ನೋಂದಾಯಿತ ತಯಾರಕರದ್ದಲ್ಲ, ಆದ್ದರಿಂದ ವಿವಾದವನ್ನು ದಾಖಲಿಸಲಾಗುವುದಿಲ್ಲ."},
"dispute_evid": {"en": "Email verified. Now send your evidence as a document or photo (for example a Certificate of Analysis), or type a short note.", "hi": "डोमेन सत्यापित । अब अपना सबूत *दस्तावेज़ या फ़ोटो* (जैसे Certificate of Analysis) के रूप में भेजें, या एक नोट लिखें।", "kn": "ಡೊಮೇನ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ . ಈಗ ನಿಮ್ಮ ಸಾಕ್ಷ್ಯವನ್ನು *ದಾಖಲೆ ಅಥವಾ ಫೋಟೋ* (ಉದಾ. Certificate of Analysis) ಆಗಿ ಕಳುಹಿಸಿ, ಅಥವಾ ಟಿಪ್ಪಣಿ ಬರೆಯಿರಿ."},
"dispute_ok": {"en": "Dispute filed for batch {b}. The batch will now show an Under review notice. The result stays the same until the regulator finishes the review.", "hi": "बैच *{b}* पर आपत्ति दर्ज हुई (स्थिति: *open*)। अब इस बैच के नतीजे के साथ *समीक्षा में* सूचना दिखेगी। नियामक की समीक्षा पूरी होने तक नतीजा वही रहेगा।", "kn": "ಬ್ಯಾಚ್ *{b}* ಗೆ ಆಕ್ಷೇಪ ದಾಖಲಿಸಲಾಗಿದೆ (ಸ್ಥಿತಿ: *open*). ಈ ಬ್ಯಾಚ್‌ನ ಫಲಿತಾಂಶದೊಂದಿಗೆ ಈಗ *ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ* ಸೂಚನೆ ಇರುತ್ತದೆ. ನಿಯಂತ್ರಕರ ಪರಿಶೀಲನೆ ಮುಗಿಯುವವರೆಗೆ ಫಲಿತಾಂಶ ಹಾಗೆಯೇ ಇರುತ್ತದೆ."},
"dispute_cap":{"en": "This company domain has reached today's limit of 10 disputes. Please try again tomorrow.",
               "hi": "इस कंपनी डोमेन की आज की 10 आपत्तियों की सीमा पूरी हो गई। कृपया कल फिर कोशिश करें।",
               "kn": "ಈ ಕಂಪನಿ ಡೊಮೇನ್‌ನ ಇಂದಿನ 10 ಆಕ್ಷೇಪಗಳ ಮಿತಿ ತಲುಪಿದೆ. ದಯವಿಟ್ಟು ನಾಳೆ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ."},
"dispute_banner": {"en": "Under review: the manufacturer has disputed this record. The result above still applies until the review ends.", "hi": "समीक्षा में: निर्माता ने इस रिकॉर्ड पर आपत्ति जताई है। समीक्षा पूरी होने तक ऊपर का नतीजा लागू है।", "kn": "ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ: ತಯಾರಕರು ಈ ದಾಖಲೆಯನ್ನು ಪ್ರಶ್ನಿಸಿದ್ದಾರೆ. ಪರಿಶೀಲನೆ ಮುಗಿಯುವವರೆಗೆ ಮೇಲಿನ ಫಲಿತಾಂಶ ಅನ್ವಯಿಸುತ್ತದೆ."},
"delete_confirm": {"en": "This will erase your language choice, your consent record and any photos not attached to an open report. Reply YES to confirm.", "hi": "इससे आपकी भाषा का चुनाव, सहमति का रिकॉर्ड और किसी खुली रिपोर्ट से न जुड़ी फ़ोटो मिट जाएँगी। पुष्टि के लिए *YES* लिखें।", "kn": "ಇದು ನಿಮ್ಮ ಭಾಷೆಯ ಆಯ್ಕೆ, ಒಪ್ಪಿಗೆ ದಾಖಲೆ ಮತ್ತು ತೆರೆದ ವರದಿಗೆ ಜೋಡಿಸದ ಫೋಟೋಗಳನ್ನು ಅಳಿಸುತ್ತದೆ. ಖಚಿತಪಡಿಸಲು *YES* ಎಂದು ಬರೆಯಿರಿ."},
"delete_done": {"en": "Done. Your data has been erased. Reports already filed stay with the regulator until they are resolved. Message me any time to start again.", "hi": "हो गया। आपका डेटा मिटा दिया गया है। जो रिपोर्ट पहले दर्ज हो चुकी हैं, वे समाधान तक नियामक के पास रहेंगी। दोबारा शुरू करने के लिए कभी भी संदेश भेजें।", "kn": "ಆಯಿತು. ನಿಮ್ಮ ಡೇಟಾ ಅಳಿಸಲಾಗಿದೆ. ಈಗಾಗಲೇ ಸಲ್ಲಿಸಿದ ವರದಿಗಳು ಪರಿಹಾರವಾಗುವವರೆಗೆ ನಿಯಂತ್ರಕರ ಬಳಿ ಇರುತ್ತವೆ. ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಲು ಯಾವಾಗ ಬೇಕಾದರೂ ಸಂದೇಶ ಕಳುಹಿಸಿ."},
"demo_tag": {"en": "Demo dataset: this record is synthetic and for illustration only.", "hi": "डेमो डेटा: यह रिकॉर्ड कृत्रिम है और केवल उदाहरण के लिए है।", "kn": "ಡೆಮೊ ಡೇಟಾ: ಈ ದಾಖಲೆ ಕೃತಕ, ಉದಾಹರಣೆಗಾಗಿ ಮಾತ್ರ."},
"preview_tag": {"en": "Preview: the copy-pattern check runs on synthetic demo data.", "hi": "प्रीव्यू: नकल-पैटर्न जाँच कृत्रिम डेमो डेटा पर चलती है।", "kn": "ಪ್ರೀವ್ಯೂ: ನಕಲು-ಮಾದರಿ ಪರಿಶೀಲನೆ ಕೃತಕ ಡೆಮೊ ಡೇಟಾದ ಮೇಲೆ ನಡೆಯುತ್ತದೆ."},
"unknown": {"en": "Sorry, I did not understand that. Please send a batch number (for example AX2291) or a photo of the pack. Send MENU for help.", "hi": "मैं समझ नहीं पाया। *बैच नंबर* (जैसे AX2291) या पैक की *फ़ोटो* भेजें। मदद के लिए *MENU* लिखें।", "kn": "ನನಗೆ ಅರ್ಥವಾಗಲಿಲ್ಲ. *ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ* (ಉದಾ. AX2291) ಅಥವಾ ಪ್ಯಾಕ್‌ನ *ಫೋಟೋ* ಕಳುಹಿಸಿ. ಸಹಾಯಕ್ಕಾಗಿ *MENU* ಎಂದು ಬರೆಯಿರಿ."},
"help": {"en": "You can send:\n- a batch number or a photo of the pack, to check it\n- WHY: how the last result was worked out\n- TIMELINE <batch>: official history of a batch\n- REPORT: report the last batch you checked\n- DISPUTE [batch]: for manufacturers only\n- LANG: change language\n- DELETE: erase your data\n- MENU: start again", "hi": "*कमांड*\n• *MENU* — फिर से शुरू\n• *LANG* — भाषा बदलें\n• *WHY* — पिछले नतीजे के स्रोत\n• *TIMELINE <बैच>* — बैच का आधिकारिक इतिहास\n• *REPORT* — पिछला जाँचा बैच रिपोर्ट करें\n• *DISPUTE [बैच]* — केवल निर्माता\n• *DELETE* — अपना डेटा मिटाएँ\n\nया सीधे *बैच नंबर* या पैक की *फ़ोटो* भेजें।", "kn": "*ಆಜ್ಞೆಗಳು*\n• *MENU* — ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಿ\n• *LANG* — ಭಾಷೆ ಬದಲಿಸಿ\n• *WHY* — ಕೊನೆಯ ಫಲಿತಾಂಶದ ಮೂಲಗಳು\n• *TIMELINE <ಬ್ಯಾಚ್>* — ಬ್ಯಾಚ್‌ನ ಅಧಿಕೃತ ಇತಿಹಾಸ\n• *REPORT* — ಕೊನೆಯ ಬ್ಯಾಚ್ ವರದಿ ಮಾಡಿ\n• *DISPUTE [ಬ್ಯಾಚ್]* — ತಯಾರಕರಿಗೆ ಮಾತ್ರ\n• *DELETE* — ನಿಮ್ಮ ಡೇಟಾ ಅಳಿಸಿ\n\nಅಥವಾ ನೇರವಾಗಿ *ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ* ಅಥವಾ ಪ್ಯಾಕ್‌ನ *ಫೋಟೋ* ಕಳುಹಿಸಿ."},
"timeline_usage": {"en": "Send TIMELINE followed by the batch number, for example TIMELINE AX2291.", "hi": "*TIMELINE <बैच>* भेजें — जैसे *TIMELINE AX2291*।", "kn": "*TIMELINE <ಬ್ಯಾಚ್>* ಕಳುಹಿಸಿ — ಉದಾ. *TIMELINE AX2291*."},
"unsupported": {"en": "I can only read text and photos. Please type the batch number or send a photo of the pack.", "hi": "मैं केवल *टेक्स्ट* और *फ़ोटो* पढ़ सकता हूँ। कृपया बैच नंबर लिखें या पैक की फ़ोटो भेजें।", "kn": "ನಾನು *ಪಠ್ಯ* ಮತ್ತು *ಫೋಟೋ* ಮಾತ್ರ ಓದಬಲ್ಲೆ. ದಯವಿಟ್ಟು ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಪ್ಯಾಕ್‌ನ ಫೋಟೋ ಕಳುಹಿಸಿ."},
"media_bad": {"en": "I could not use that file. Please send a JPEG, PNG, WebP or PDF under 10 MB.", "hi": "मैं वह फ़ाइल इस्तेमाल नहीं कर सका। कृपया 10 MB से छोटी *JPEG, PNG, WebP या PDF* भेजें।", "kn": "ಆ ಫೈಲ್ ಬಳಸಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು 10 MB ಗಿಂತ ಚಿಕ್ಕದಾದ *JPEG, PNG, WebP ಅಥವಾ PDF* ಕಳುಹಿಸಿ."},
"report_photo_ok": {"en": "Photo added to your report.", "hi": "आपकी रिपोर्ट में फ़ोटो जोड़ दी गई है।", "kn": "ನಿಮ್ಮ ವರದಿಗೆ ಫೋಟೋ ಸೇರಿಸಲಾಗಿದೆ."},
"degraded": {"en": "Official records cannot be reached right now, so this result is incomplete. Do not treat it as an all-clear.", "hi": "आधिकारिक रिकॉर्ड अभी उपलब्ध नहीं हैं, इसलिए यह नतीजा अधूरा है। इसे सब ठीक होने का संकेत न समझें।", "kn": "ಅಧಿಕೃತ ದಾಖಲೆಗಳು ಈಗ ಲಭ್ಯವಿಲ್ಲ, ಆದ್ದರಿಂದ ಈ ಫಲಿತಾಂಶ ಅಪೂರ್ಣ. ಇದನ್ನು ಎಲ್ಲವೂ ಸರಿ ಎಂಬ ಸೂಚನೆ ಎಂದು ಪರಿಗಣಿಸಬೇಡಿ."},
"error": {"en": "Sorry, something went wrong on my side. Please send the batch number again in a moment.", "hi": "क्षमा करें — मेरी ओर से कुछ गड़बड़ हो गई। कृपया थोड़ी देर बाद बैच नंबर फिर भेजें।", "kn": "ಕ್ಷಮಿಸಿ — ನನ್ನ ಕಡೆಯಿಂದ ಏನೋ ತಪ್ಪಾಯಿತು. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ ಮತ್ತೆ ಕಳುಹಿಸಿ."},
}

VERDICT = {   # heading + Safe Action. "escalated" is a RED variant. AMBER-escalated row from v1 removed (v1 9.4/9.5 contradicted).
 "RED_nsq":  {"head": {"en": "RED — STOP", "hi": "लाल — रुकें", "kn": "ಕೆಂಪು — ನಿಲ್ಲಿಸಿ"},
   "action": {"en": "Do not consume. Show this result to a pharmacist. Keep the packaging.",
              "hi": "इसे न खाएँ। यह नतीजा फ़ार्मासिस्ट को दिखाएँ। पैकेट संभालकर रखें।",
              "kn": "ಇದನ್ನು ಸೇವಿಸಬೇಡಿ. ಈ ಫಲಿತಾಂಶವನ್ನು ಔಷಧಿಕಾರರಿಗೆ ತೋರಿಸಿ. ಪ್ಯಾಕೆಟ್ ಜೋಪಾನವಾಗಿ ಇಟ್ಟುಕೊಳ್ಳಿ."}},
 "RED_escalated": {"head": {"en": "RED — STOP (escalated)", "hi": "लाल — रुकें (बढ़ाया गया)", "kn": "ಕೆಂಪು — ನಿಲ್ಲಿಸಿ (ಹೆಚ್ಚಿಸಲಾಗಿದೆ)"},
   "action": {"en": "Do not consume. This pack shows signs of tampering or inconsistency. Keep the packaging and report it.",
              "hi": "इसे न खाएँ। इस पैक में छेड़छाड़ या गड़बड़ी के संकेत हैं। पैकेट रखें और रिपोर्ट करें।",
              "kn": "ಇದನ್ನು ಸೇವಿಸಬೇಡಿ. ಈ ಪ್ಯಾಕ್‌ನಲ್ಲಿ ಬದಲಾವಣೆ ಅಥವಾ ಅಸಂಗತಿಯ ಸೂಚನೆಗಳಿವೆ. ಪ್ಯಾಕೆಟ್ ಇಟ್ಟುಕೊಂಡು ವರದಿ ಮಾಡಿ."}},
 "EXPIRED": {"head": {"en": "EXPIRED", "hi": "एक्सपायर", "kn": "ಅವಧಿ ಮುಗಿದಿದೆ"},
   "action": {"en": "Do not use — this pack has expired. Dispose of it safely. No report needed unless you also suspect tampering.",
              "hi": "इसका उपयोग न करें — यह दवा एक्सपायर हो चुकी है। इसे सुरक्षित तरीके से फेंक दें।",
              "kn": "ಇದನ್ನು ಬಳಸಬೇಡಿ — ಈ ಔಷಧದ ಅವಧಿ ಮುಗಿದಿದೆ. ಸುರಕ್ಷಿತವಾಗಿ ವಿಲೇವಾರಿ ಮಾಡಿ."}},
 "AMBER": {"head": {"en": "AMBER — CHECK FURTHER", "hi": "पीला — आगे जाँचें", "kn": "ಹಳದಿ — ಮತ್ತಷ್ಟು ಪರಿಶೀಲಿಸಿ"},
   "action": {"en": "Don't discard yet — confirm with your pharmacist before use.",
              "hi": "अभी फेंकें नहीं — इस्तेमाल से पहले अपने फ़ार्मासिस्ट से पुष्टि करें।",
              "kn": "ಇನ್ನೂ ಎಸೆಯಬೇಡಿ — ಬಳಸುವ ಮೊದಲು ನಿಮ್ಮ ಔಷಧಿಕಾರರೊಂದಿಗೆ ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ."}},
 "GREEN": {"head": {"en": "GREEN — NO WARNING FOUND", "hi": "हरा — कोई चेतावनी नहीं", "kn": "ಹಸಿರು — ಎಚ್ಚರಿಕೆ ಇಲ್ಲ"},
   "action": {"en": "No warnings found in our records. This does not confirm authenticity — always buy from a licensed pharmacy.",
              "hi": "हमारे रिकॉर्ड में कोई चेतावनी नहीं मिली। इसका मतलब असली होना पक्का नहीं है — हमेशा लाइसेंसशुदा फ़ार्मेसी से ही खरीदें।",
              "kn": "ನಮ್ಮ ದಾಖಲೆಗಳಲ್ಲಿ ಯಾವುದೇ ಎಚ್ಚರಿಕೆ ಕಂಡುಬಂದಿಲ್ಲ. ಇದು ಅಸಲಿ ಎಂದು ಖಚಿತಪಡಿಸುವುದಿಲ್ಲ — ಯಾವಾಗಲೂ ಪರವಾನಗಿ ಪಡೆದ ಔಷಧಾಲಯದಿಂದ ಖರೀದಿಸಿ."}},
}

def t(key, lang="en", **kw):
    d = S[key]; s = d.get(lang) or d["en"]
    return s.format(**kw) if kw else s

def verdict_key(v):
    if v.verdict == "RED": return "RED_escalated" if v.reason == "escalated_conflict" else "RED_nsq"
    return v.verdict
